$(document).ready(function () {
  const scales = {
    level_1: [
      {
        key: "C",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "1 octave",
      },
      {
        key: "G",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "1 octave",
      },
      {
        key: "G",
        type: "major",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "1 octave",
      },
      {
        key: "G",
        type: "major",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "1 octave",
      },
      {
        key: "A",
        type: "minor",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "1 octave",
      },
      {
        key: "A",
        type: "minor",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "1 octave",
      },
    ],
    level_2: [
      {
        key: "G",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "chromatic",
        motion: "Scales",
        hands: "Left hand",
        octave: "1 octave",
      },
      {
        key: "D",
        type: "chromatic",
        motion: "Scales",
        hands: "Right hand",
        octave: "1 octave",
      },
      {
        key: "D",
        type: "major",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "major",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
    ],
    level_3: [
      {
        key: "D",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Hands together",
        octave: "1 octave",
      },
      {
        key: "D",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
    ],
    level_4: [
      {
        key: "B♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "chromatic",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "Bb",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
    ],
    level_5: [
      {
        key: "A",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "D♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "G#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "minor (staccato)",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "D♭",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "A#",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "D♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "G#",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "Diminished 7th",
        motion: "Arpeggios",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "Diminished 7th",
        motion: "Arpeggios",
        hands: "Right hand",
        octave: "2 octaves",
      },
    ],
    level_6: [
      {
        key: "D",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "D",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "D",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "D",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "D",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "D",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "G#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "G#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Contrary Motion Scales
      {
        key: "D",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "D",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "G#",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "2 octaves",
      },
      // Chromatic Scales
      {
        key: "G#",
        type: "chromatic",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "G#",
        type: "chromatic",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "G#",
        type: "chromatic",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "chromatic",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "chromatic",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "chromatic",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Arpeggios
      {
        key: "D",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "D",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G#",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Dominant 7th Arpeggios
      {
        key: "D",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A♭",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Diminished 7th Arpeggios
      {
        key: "G#",
        type: "Diminished 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B",
        type: "Diminished 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
    ],
    level_7: [
      // Similar Motion Scales
      {
        key: "D♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "D♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "D♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Scales a 3rd apart
      {
        key: "D♭",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "D♭",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "D♭",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Scales a 3rd apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Scales a 3rd apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Contrary Motion Scales
      {
        key: "D♭",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Scales in 3rds
      {
        key: "G",
        type: "major",
        motion: "Scale in 3rds",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scale in 3rds",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Scale in 3rds",
        hands: "Hands together",
        octave: "2 octaves",
      },
      // Staccato Scales
      {
        key: "G",
        type: "major",
        motion: "Staccato",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Staccato",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Staccato",
        hands: "Hands together",
        octave: "2 octaves",
      },
      // Chromatic Scales
      {
        key: "C#",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "C#",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "C#",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "E",
        type: "chromatic",
        motion: "Scales (Contrary Motion)",
        hands: "Hands together",
        octave: "2 octaves",
      },
      // Arpeggios
      {
        key: "D♭",
        type: "major",
        motion: "Arpeggios (1st inversion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C#",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Dominant 7th Arpeggios
      {
        key: "D♭",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "G",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "B♭",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Diminished 7th Arpeggios
      {
        key: "B♭",
        type: "Diminished 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "Diminished 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
    ],
    level_8: [
      // Similar Motion Scales
      {
        key: "C",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales (similar motion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Scales a 6th apart
      {
        key: "C",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Scales a 6th apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Scales a 6th apart",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Contrary Motion Scales
      {
        key: "C",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Contrary Motion",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Scales in 3rds
      {
        key: "E♭",
        type: "major",
        motion: "Scale in 3rds",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scale in 3rds",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Scale in 3rds",
        hands: "Hands together",
        octave: "2 octaves",
      },
      // Scales in 6ths
      {
        key: "C",
        type: "major",
        motion: "Scales in 6ths",
        hands: "Left hand",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "major",
        motion: "Scales in 6ths",
        hands: "Right hand",
        octave: "2 octaves",
      },
      {
        key: "C",
        type: "major",
        motion: "Scales in 6ths",
        hands: "Hands together",
        octave: "2 octaves",
      },
      // Chromatic Scales
      {
        key: "E♭",
        type: "chromatic",
        motion: "Scales",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "chromatic",
        motion: "Scales",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "chromatic",
        motion: "Scales",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "chromatic",
        motion: "Scales",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "chromatic",
        motion: "Scales",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "chromatic",
        motion: "Scales",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Whole Tone Scales
      {
        key: "E♭",
        type: "whole tone",
        motion: "Scales",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "whole tone",
        motion: "Scales",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "whole tone",
        motion: "Scales",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "whole tone",
        motion: "Scales",
        hands: "Left hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "whole tone",
        motion: "Scales",
        hands: "Right hand",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "whole tone",
        motion: "Scales",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Arpeggios
      {
        key: "C",
        type: "major",
        motion: "Arpeggios (2nd inversion)",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "major",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E♭",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "minor",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Dominant 7th Arpeggios
      {
        key: "C",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "E",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "F#",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "A",
        type: "Dominant 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      // Diminished 7th Arpeggios
      {
        key: "E♭",
        type: "Diminished 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
      {
        key: "C",
        type: "Diminished 7th",
        motion: "Arpeggios",
        hands: "Hands together",
        octave: "4 octaves",
      },
    ],
  };

  $("#randomize-btn").click(function () {
    // Get the selected grade value
    const selectedGrade = $("select[name='level']").val();

    // Determine the level based on the selected grade
    const randomScale =
      scales[selectedGrade][
        Math.floor(Math.random() * scales[selectedGrade].length)
      ];

    // Update the text elements with the selected scale's properties
    $("#key").text(randomScale.key);
    $("#type").text(randomScale.type);
    $("#motion").text(randomScale.motion);
    $("#octave").text(randomScale.octave);
    $("#hands").text(randomScale.hands);

    // Update the opacity of the hand indicators
    $("#left-hand").toggleClass(
      "opacity-30",
      randomScale.hands !== "Hands together" &&
        randomScale.hands !== "Left hand"
    );
    $("#left-hand").toggleClass(
      "opacity-100",
      randomScale.hands === "Hands together" ||
        randomScale.hands === "Left hand"
    );
    $("#right-hand").toggleClass(
      "opacity-30",
      randomScale.hands !== "Hands together" &&
        randomScale.hands !== "Right hand"
    );
    $("#right-hand").toggleClass(
      "opacity-100",
      randomScale.hands === "Hands together" ||
        randomScale.hands === "Right hand"
    );
  });
});
